#! /usr/bin/env zsh

# SOFT-LINK OUTWARDS
attempt linkup -s bin ~

# HARD-LINK OUTWARDS
attempt linkup zshrc ~/.zshrc
attempt linkup vimrc ~/.vimrc
attempt linkup aliases ~/.aliases
attempt linkup MAIN.zsh-theme ~/.oh-my-zsh/custom/themes
attempt linkup kuaa.m3u ~/Documents
attempt linkup gitconfig ~/.gitconfig
attempt linkup com.apple.dock.plist ~/Library/Preferences

# SHOULD BE RUN
# - mac-gitignore
# TODO before running make reusable "done" flag system and create board for other related features after that

# MISC. CONSIDER
# - subl

# MISC. TODO
# - abstract away some OS dir hierarchy differences
#   + make a device file that erases the mac/linux distinctions on some useful dirs,
# 	  like Application support vs .dirs
# - dict of rules for linking onto a machine, and script to execute them
# - write alias to check if file is already a hardlink to another file
# - chmod +x on binaries including those that get linked to ~/bin
# - soft links are having more issues than hard??
